



char* update_html = 
"<script src='https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js'></script>"
"<form method='POST' action='#' enctype='multipart/form-data' id='upload_form'>"
"  <input type='file' name='update'>"
"  <input type='submit' value='Update'>"
"</form>"
"<div id='prg'>progress: 0%</div>"
"<script>"
"  $('form').submit(function(e){"
"    e.preventDefault();"
"    var form = $('#upload_form')[0];"
"    var data = new FormData(form);"
"     $.ajax({"
"      url: '/update_backend',"
"      type: 'POST',"
"      data: data,"
"      contentType: false,"
"      processData:false,"
"      xhr: function() {"
"        var xhr = new window.XMLHttpRequest();"
"        xhr.upload.addEventListener('progress', function(evt) {"
"          if (evt.lengthComputable) {"
"            var per = evt.loaded / evt.total;"
"            $('#prg').html('progress: ' + Math.round(per*100) + '%');"
"          }"
"        }, false);"
"        return xhr;"
"      },"
"      success:function(d, s) {"
"        console.log('success!')"
"      },"
"      error: function (a, b, c) {"
"      }"
"    });"
"  });"
"</script>";



// Pardon the html mess. Gotta tell the browser to not make the text super tiny.
char *main_page_html =
"<!DOCTYPE html><html><head><title>Driveway Lights</title></head><body><p style=\"font-size:36px\">"
    "<script>"
    "  function pulse() {"
    "    var xhttp = new XMLHttpRequest();"
    "    xhttp.open('POST', 'pulse_lights', true);"
    "    xhttp.onload = function(){"
    "      console.log(this.responseText);"
    "      const pb = document.getElementById('pulse_button');"
    "      const cb = document.getElementById('cancel_button');"
    "      const ls = document.getElementById('lights_span');"
    "      const os = document.getElementById('outer_span');"
    "      if(this.responseText.startsWith('on')) {"
    "        ls.innerHTML = 'ON';"
    "        ls.style = 'color:Green;';"
    "        if(this.responseText.endsWith('on')) {"
    "          os.innerHTML = 'because the main switch is on';"
    "          pb.style.display = 'none';"
    "          cb.style.display = 'none';"
    "        } else {"
    "          os.innerHTML = 'for ' + this.responseText.substring(this.responseText.indexOf(':') + 1);"
    "          pb.style.display = 'block';"
    "          cb.style.display = 'block';"
    "          pb.value = 'Restart Timer';"
    "        }"
    "      } else {"
    "        ls.innerHTML = 'OFF';"
    "        ls.style = 'color:Red;';"
    "        pb.style.display = 'block';"
    "        cb.style.display = 'none';"
    "        pb.value = 'Turn On';"
    "      }"
    "    };"
    "    xhttp.send('poop');"
    "  }"
    "  function cancel_now() {"
    "    var xhttp = new XMLHttpRequest();"
    "    xhttp.open('POST', 'cancel_lights', true);"
    "    xhttp.onload = function(){"
    "      console.log(this.responseText);"
    "      const pb = document.getElementById('pulse_button');"
    "      const cb = document.getElementById('cancel_button');"
    "      const ls = document.getElementById('lights_span');"
    "      const os = document.getElementById('outer_span');"
    "      if(this.responseText.startsWith('ok')) {"
    "        ls.innerHTML = 'OFF';"
    "        ls.style = 'color:Red;';"
    "        pb.style.display = 'block';"
    "        cb.style.display = 'none';"
    "        pb.value = 'Turn On';"
    "        os.innerHTML = '';"
    "      } else {"
    "        ls.innerHTML = 'ON';"
    "        ls.style = 'color:Green;';"
    "        os.innerHTML = 'because the main switch is on';"
    "        pb.style.display = 'none';"
    "        cb.style.display = 'none';"
    "      }"
    "    };"
    "    xhttp.send('poop');"
    "  }"
    "</script>"
  "<span style=\"font-size:90px\">";